# Generated by Django 6.0.6 on 2026-06-14 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estudantes', '0001_initial'),
        ('projetos', '0001_initial'),
        ('turmas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RelatorioEstudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(help_text='Descrição das atividades realizadas pelo estudante no projeto')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='estudantes.estudante')),
                ('projeto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='projetos.projeto')),
                ('turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relatorios', to='turmas.turma')),
            ],
            options={
                'verbose_name': 'Relatório do Estudante',
                'verbose_name_plural': 'Relatórios dos Estudantes',
                'db_table': 'relatorios_estudantes',
                'ordering': ['-data_envio'],
                'unique_together': {('estudante', 'projeto')},
            },
        ),
    ]
